version: '3'

services:
  web:
    container_name: php-apache
    build: ./php-apache
    ports:
      - 80:80
    volumes:
      - ./src/laravel:/var/www/html/laravel
      - ./php-apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    restart: always
    working_dir: /var/www/html/laravel

  db:
    container_name: mysql
    build: ./mysql
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Tokyo'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 1234:80
    environment:
      - PMA_ARBITRARY=${PMA_ARBITRARY}
      - PMA_HOST=${PMA_HOST}
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    volumes:
      - /sessions
